# Build and configuration of database image and app Dockerfile in containers
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file: ".env"
    networks:
      - sso-network
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_DB: $DB_NAME
      PGDATA: "/var/lib/postgresql/data/sso_data"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/sso_data/
      - ./pg_notify:/var/lib/postgresql/data/sso_data/
    ports:
      - $DB_PORT:$DB_PORT
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    command: >
      postgres -c max_connections=1000
                     -c shared_buffers=256MB
                     -c effective_cache_size=768MB
                     -c maintenance_work_mem=64MB
                     -c checkpoint_completion_target=0.7
                     -c wal_buffers=16MB
                     -c default_statistics_target=100
  migrator:
    build:
      context: ./cmd/migrator
    depends_on:
      - postgres
    env_file: ".env"
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
    networks:
      - sso-network
  sso:
    build:
      context: .
    depends_on:
      - postgres
      - migrator
    env_file: ".env"
    environment:
      DB_USER: $DB_USER
      DB_PASS: $DB_PASS
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_NAME: $DB_NAME
    ports:
      - $SSO_PORT:$SSO_PORT
    networks:
      - sso-network
volumes:
  pgdata:
    driver: local
networks:
  sso-network:
    driver: bridge