services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "sso_db"
      PGDATA: "/var/lib/postgresql/data/sso_data"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/sso_data/
      - ./pg_notify:/var/lib/postgresql/data/sso_data/
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    command: >
      postgres -c max_connections=1000
                     -c shared_buffers=256MB
                     -c effective_cache_size=768MB
                     -c maintenance_work_mem=64MB
                     -c checkpoint_completion_target=0.7
                     -c wal_buffers=16MB
                     -c default_statistics_target=100
volumes:
  pgdata:
    driver: local