env: "dev" #dev, prod
conn_string: "postgres:postgres@localhost:5433/sso_db" #currently unused
token_ttl: 15m
refresh_token_ttl: 24h
session_ttl: 48h
session_enabled: true
authorization_code_ttl: 5m
use_cache: true
grpc:
  port: 44043
  timeout: 1h
redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  session_ttl: 15m
  email_auth_token_ttl: 24h
  password_reset_token_ttl: 1h
jwt:
  token_ttls:
    0: 1h
    1: 30m
  allowed_claims:
    0:
      - iss
      - aud
      - iat
      - exp
      - sub
      - email
      - is_verified
    1:
      - iss
      - aud
      - exp
      - sub
      - scope